name: CI
on:
  push:
    branches: ['main']
  workflow_dispatch: {}
jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - run: ls -la